export const ADD_TODO = 'ADD_TODO'
export const CLEAR_ALL = 'CLEAR_ALL'
export const REMOVE_TODO = 'REMOVE_TODO'
export const failGenRandNum = 'failGenRandNum'
export const successGenRandNum = 'successGenRandNum'
